// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/log_collector.proto
//
// This file is hand-written to mirror the output of protoc-gen-go v1.34 against
// the companion log_collector.proto. It is kept in sync with
// git.woa.com/PromptHub/log_collector/proto/log_collector.pb.go at the wire
// protocol level; only the go_package path differs.

// Package proto contains the generated protobuf stubs for the log_collector
// service. These are consumed by the TRPCWriter in the parent package to
// upload execution traces.
package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportTraceRequest 上报追踪请求
type ReportTraceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Caller 调用方服务名，格式: trpc.${app}.${server}
	Caller string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	// TraceJson Prompt 执行追踪 JSON
	TraceJson string `protobuf:"bytes,2,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	// Token 业务隔离标识，用于区分不同业务的 Trace 数据
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

// Reset resets the ReportTraceRequest to the zero value.
func (x *ReportTraceRequest) Reset() {
	*x = ReportTraceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &fileLogCollectorProtoMsgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

// String returns the string representation of the ReportTraceRequest.
func (x *ReportTraceRequest) String() string { return protoimpl.X.MessageStringOf(x) }

// ProtoMessage marks ReportTraceRequest as a protobuf message.
func (*ReportTraceRequest) ProtoMessage() {}

// ProtoReflect returns the protobuf message reflection descriptor.
func (x *ReportTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &fileLogCollectorProtoMsgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// GetCaller returns the caller field.
func (x *ReportTraceRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

// GetTraceJson returns the trace_json field.
func (x *ReportTraceRequest) GetTraceJson() string {
	if x != nil {
		return x.TraceJson
	}
	return ""
}

// GetToken returns the token field.
func (x *ReportTraceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ReportTraceResponse 上报追踪响应
type ReportTraceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code 响应码，0=成功, 非0=失败
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message 错误信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

// Reset resets the ReportTraceResponse to the zero value.
func (x *ReportTraceResponse) Reset() {
	*x = ReportTraceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &fileLogCollectorProtoMsgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

// String returns the string representation of the ReportTraceResponse.
func (x *ReportTraceResponse) String() string { return protoimpl.X.MessageStringOf(x) }

// ProtoMessage marks ReportTraceResponse as a protobuf message.
func (*ReportTraceResponse) ProtoMessage() {}

// ProtoReflect returns the protobuf message reflection descriptor.
func (x *ReportTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &fileLogCollectorProtoMsgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// GetCode returns the code field.
func (x *ReportTraceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// GetMessage returns the message field.
func (x *ReportTraceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// File descriptor. The raw descriptor is encoded as produced by protoc so that
// protoreflect can resolve message types at runtime.
var fileLogCollectorProto protoreflect.FileDescriptor

// fileLogCollectorProtoRawDesc is the raw proto descriptor (wire-compatible
// with log_collector/proto/log_collector.pb.go). The go_package option is the
// only differing field; its bytes are patched at init time below.
var fileLogCollectorProtoRawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x74, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x61, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x63, 0x65, 0x4a, 0x73,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x7a, 0x0a,
	0x0c, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x6a, 0x0a,
	0x0b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x2c, 0x2e, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x74, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x2e, 0x77, 0x6f, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x48,
	0x75, 0x62, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	fileLogCollectorProtoRawDescOnce sync.Once
	fileLogCollectorProtoRawDescData = fileLogCollectorProtoRawDesc
)

func fileLogCollectorProtoRawDescGZIP() []byte {
	fileLogCollectorProtoRawDescOnce.Do(func() {
		fileLogCollectorProtoRawDescData = protoimpl.X.CompressGZIP(fileLogCollectorProtoRawDescData)
	})
	return fileLogCollectorProtoRawDescData
}

var fileLogCollectorProtoMsgTypes = make([]protoimpl.MessageInfo, 2)
var fileLogCollectorProtoGoTypes = []any{
	(*ReportTraceRequest)(nil),  // 0: trpc.prompt.logcollector.ReportTraceRequest
	(*ReportTraceResponse)(nil), // 1: trpc.prompt.logcollector.ReportTraceResponse
}
var fileLogCollectorProtoDepIdxs = []int32{
	0, // 0: trpc.prompt.logcollector.LogCollector.ReportTrace:input_type -> trpc.prompt.logcollector.ReportTraceRequest
	1, // 1: trpc.prompt.logcollector.LogCollector.ReportTrace:output_type -> trpc.prompt.logcollector.ReportTraceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { fileLogCollectorProtoInit() }

func fileLogCollectorProtoInit() {
	if fileLogCollectorProto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		fileLogCollectorProtoMsgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReportTraceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		fileLogCollectorProtoMsgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReportTraceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: fileLogCollectorProtoRawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           fileLogCollectorProtoGoTypes,
		DependencyIndexes: fileLogCollectorProtoDepIdxs,
		MessageInfos:      fileLogCollectorProtoMsgTypes,
	}.Build()
	fileLogCollectorProto = out.File
	fileLogCollectorProtoRawDesc = nil
	fileLogCollectorProtoGoTypes = nil
	fileLogCollectorProtoDepIdxs = nil
}
