// Code generated by trpc-go/trpc-go-cmdline. DO NOT EDIT.
// source: log_collector.proto
//
// This file is hand-written to mirror the tRPC client/server stub produced by
// trpc-go-cmdline against log_collector.proto, but using the open-source trpc
// import path ("trpc.group/trpc-go/trpc-go") so that trpc-agent-go consumers
// do not need the internal "git.code.oa.com/trpc-go/trpc-go" distribution.

package proto

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	"trpc.group/trpc-go/trpc-go/server"
)

// ---------- Server Service Definition ----------

// LogCollectorService defines service interface.
type LogCollectorService interface {
	// ReportTrace 上报 Prompt 执行追踪数据
	ReportTrace(ctx context.Context, req *ReportTraceRequest) (*ReportTraceResponse, error)
}

// LogCollectorService_ReportTrace_Handler is the generated server handler for
// the ReportTrace method.
func LogCollectorService_ReportTrace_Handler(
	svr any, ctx context.Context, f server.FilterFunc,
) (any, error) {
	req := &ReportTraceRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqBody any) (any, error) {
		return svr.(LogCollectorService).ReportTrace(ctx, reqBody.(*ReportTraceRequest))
	}
	rsp, err := filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// LogCollectorServer_ServiceDesc is the server descriptor for RegisterService.
var LogCollectorServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.trs.prompt_log_collector.LogCollector",
	HandlerType: ((*LogCollectorService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.trs.prompt_log_collector.LogCollector/ReportTrace",
			Func: LogCollectorService_ReportTrace_Handler,
		},
	},
}

// RegisterLogCollectorService registers a LogCollectorService implementation
// with a tRPC server. It is provided for symmetry with the server-side stub
// and is typically not used directly by trpc-agent-go consumers (who only
// need the client proxy).
func RegisterLogCollectorService(s server.Service, svr LogCollectorService) {
	if err := s.Register(&LogCollectorServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("LogCollector register error: %v", err))
	}
}

// UnimplementedLogCollector is the default unimplemented server.
type UnimplementedLogCollector struct{}

// ReportTrace returns an unimplemented error by default. Embed
// UnimplementedLogCollector in your server implementation for forward
// compatibility.
func (s *UnimplementedLogCollector) ReportTrace(
	ctx context.Context, req *ReportTraceRequest,
) (*ReportTraceResponse, error) {
	return nil, errors.New("rpc ReportTrace of service LogCollector is not implemented")
}

// ---------- Client Service Definition ----------

// LogCollectorClientProxy defines client proxy interface for LogCollector.
type LogCollectorClientProxy interface {
	// ReportTrace 上报 Prompt 执行追踪数据
	ReportTrace(
		ctx context.Context, req *ReportTraceRequest, opts ...client.Option,
	) (rsp *ReportTraceResponse, err error)
}

// LogCollectorClientProxyImpl is the default client proxy implementation.
type LogCollectorClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

// NewLogCollectorClientProxy creates a new client proxy using the default
// tRPC client. It can be swapped out for testing by assigning a different
// function to this variable.
var NewLogCollectorClientProxy = func(opts ...client.Option) LogCollectorClientProxy {
	return &LogCollectorClientProxyImpl{client: client.DefaultClient, opts: opts}
}

// ReportTrace implements LogCollectorClientProxy.
func (c *LogCollectorClientProxyImpl) ReportTrace(
	ctx context.Context, req *ReportTraceRequest, opts ...client.Option,
) (*ReportTraceResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.trs.prompt_log_collector.LogCollector/ReportTrace")
	msg.WithCalleeServiceName(LogCollectorServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("trs")
	msg.WithCalleeServer("prompt_log_collector")
	msg.WithCalleeService("LogCollector")
	msg.WithCalleeMethod("ReportTrace")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReportTraceResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}
